<?php

use Illuminate\Database\Seeder;

class UserRolesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_roles')->delete();
        
        \DB::table('user_roles')->insert(array (
            0 =>
                array (
                    'name' => 'Administrator',
                    'description' => 'Site administrators have full access to all functions',
                    'frames' => 1,
                    'home' => 1,
                    'view_document' => 1,
                    'new_document' => 1,
                    'save_document' => 1,
                    'publish_document' => 1,
                    'delete_document' => 1,
                    'empty_trash' => 1,
                    'action_ok' => 1,
                    'logout' => 1,
                    'help' => 1,
                    'messages' => 1,
                    'new_user' => 1,
                    'edit_user' => 1,
                    'logs' => 1,
                    'edit_parser' => 1,
                    'save_parser' => 1,
                    'edit_template' => 1,
                    'settings' => 1,
                    'credits' => 1,
                    'new_template' => 1,
                    'save_template' => 1,
                    'delete_template' => 1,
                    'edit_snippet' => 1,
                    'new_snippet' => 1,
                    'save_snippet' => 1,
                    'delete_snippet' => 1,
                    'edit_chunk' => 1,
                    'new_chunk' => 1,
                    'save_chunk' => 1,
                    'delete_chunk' => 1,
                    'empty_cache' => 1,
                    'edit_document' => 1,
                    'change_password' => 1,
                    'error_dialog' => 1,
                    'about' => 1,
                    'category_manager' => 1,
                    'file_manager' => 1,
                    'assets_files' => 1,
                    'assets_images' => 1,
                    'save_user' => 1,
                    'delete_user' => 1,
                    'save_password' => 1,
                    'edit_role' => 1,
                    'save_role' => 1,
                    'delete_role' => 1,
                    'new_role' => 1,
                    'access_permissions' => 1,
                    'bk_manager' => 1,
                    'new_plugin' => 1,
                    'edit_plugin' => 1,
                    'save_plugin' => 1,
                    'delete_plugin' => 1,
                    'new_module' => 1,
                    'edit_module' => 1,
                    'save_module' => 1,
                    'delete_module' => 1,
                    'exec_module' => 1,
                    'view_eventlog' => 1,
                    'delete_eventlog' => 1,
                    'new_web_user' => 1,
                    'edit_web_user' => 1,
                    'save_web_user' => 1,
                    'delete_web_user' => 1,
                    'web_access_permissions' => 1,
                    'view_unpublished' => 1,
                    'import_static' => 1,
                    'export_static' => 1,
                    'remove_locks' => 1,
                    'display_locks' => 1,
                    'change_resourcetype' => 1,
                ),
            1 =>
            array (
                'name' => 'Editor',
                'description' => 'Limited to managing content',
                'frames' => 1,
                'home' => 1,
                'view_document' => 1,
                'new_document' => 1,
                'save_document' => 1,
                'publish_document' => 1,
                'delete_document' => 1,
                'empty_trash' => 0,
                'action_ok' => 1,
                'logout' => 1,
                'help' => 1,
                'messages' => 0,
                'new_user' => 0,
                'edit_user' => 0,
                'logs' => 0,
                'edit_parser' => 0,
                'save_parser' => 0,
                'edit_template' => 0,
                'settings' => 0,
                'credits' => 1,
                'new_template' => 0,
                'save_template' => 0,
                'delete_template' => 0,
                'edit_snippet' => 0,
                'new_snippet' => 0,
                'save_snippet' => 0,
                'delete_snippet' => 0,
                'edit_chunk' => 1,
                'new_chunk' => 0,
                'save_chunk' => 1,
                'delete_chunk' => 0,
                'empty_cache' => 1,
                'edit_document' => 1,
                'change_password' => 1,
                'error_dialog' => 1,
                'about' => 1,
                'category_manager' => 0,
                'file_manager' => 1,
                'assets_files' => 1,
                'assets_images' => 1,
                'save_user' => 0,
                'delete_user' => 0,
                'save_password' => 1,
                'edit_role' => 0,
                'save_role' => 0,
                'delete_role' => 0,
                'new_role' => 0,
                'access_permissions' => 0,
                'bk_manager' => 0,
                'new_plugin' => 0,
                'edit_plugin' => 0,
                'save_plugin' => 0,
                'delete_plugin' => 0,
                'new_module' => 0,
                'edit_module' => 0,
                'save_module' => 0,
                'delete_module' => 0,
                'exec_module' => 1,
                'view_eventlog' => 0,
                'delete_eventlog' => 0,
                'new_web_user' => 0,
                'edit_web_user' => 0,
                'save_web_user' => 0,
                'delete_web_user' => 0,
                'web_access_permissions' => 0,
                'view_unpublished' => 1,
                'import_static' => 0,
                'export_static' => 0,
                'remove_locks' => 1,
                'display_locks' => 1,
                'change_resourcetype' => 1,
            ),
            2 =>
            array (
                'name' => 'Publisher',
                'description' => 'Editor with expanded permissions including manage users, update Elements and site settings',
                'frames' => 1,
                'home' => 1,
                'view_document' => 1,
                'new_document' => 1,
                'save_document' => 1,
                'publish_document' => 1,
                'delete_document' => 1,
                'empty_trash' => 1,
                'action_ok' => 1,
                'logout' => 1,
                'help' => 1,
                'messages' => 0,
                'new_user' => 1,
                'edit_user' => 1,
                'logs' => 1,
                'edit_parser' => 0,
                'save_parser' => 0,
                'edit_template' => 1,
                'settings' => 1,
                'credits' => 1,
                'new_template' => 1,
                'save_template' => 1,
                'delete_template' => 1,
                'edit_snippet' => 0,
                'new_snippet' => 0,
                'save_snippet' => 0,
                'delete_snippet' => 0,
                'edit_chunk' => 1,
                'new_chunk' => 1,
                'save_chunk' => 1,
                'delete_chunk' => 1,
                'empty_cache' => 1,
                'edit_document' => 1,
                'change_password' => 1,
                'error_dialog' => 1,
                'about' => 1,
                'category_manager' => 0,
                'file_manager' => 1,
                'assets_files' => 1,
                'assets_images' => 1,
                'save_user' => 1,
                'delete_user' => 1,
                'save_password' => 1,
                'edit_role' => 0,
                'save_role' => 0,
                'delete_role' => 0,
                'new_role' => 0,
                'access_permissions' => 0,
                'bk_manager' => 1,
                'new_plugin' => 0,
                'edit_plugin' => 0,
                'save_plugin' => 0,
                'delete_plugin' => 0,
                'new_module' => 0,
                'edit_module' => 0,
                'save_module' => 0,
                'delete_module' => 0,
                'exec_module' => 1,
                'view_eventlog' => 0,
                'delete_eventlog' => 0,
                'new_web_user' => 1,
                'edit_web_user' => 1,
                'save_web_user' => 1,
                'delete_web_user' => 1,
                'web_access_permissions' => 0,
                'view_unpublished' => 1,
                'import_static' => 0,
                'export_static' => 0,
                'remove_locks' => 1,
                'display_locks' => 1,
                'change_resourcetype' => 1,
            )
        ));
        
        
    }
}