<?php

require_once('./minixml.inc.php');



$t1NumRows = 3;
$t1NumCols = 3;

$t2NumRows = 2;
$t2NumCols = 2;
		

$htmlDoc = new MiniXMLDoc();

$htmlArray = array(

 'html' => array(

 'head'	=> array(
		'title' => 'XML::Mini Generated HTML page',
		'style' => 'body,td,a,p,.harray(font-family:arial,sans-serif;) .qarray(text-decoration:none; color:#0000cc;)',
		),
 'body' => array(
	'bgcolor' 	=> '#ffffff',
	'link' 		=> '#0000cc',
	'vlink' 	=> '#551a8b',
	'h3'	=> 'This page was generated by XML::Mini!',
	'p'		=> array(
				array(
					'-content'	=> 'View the source of this page to take a look at',
					'a'	=> array(
							'href'	=> 'http://minixml.psychogenic.com',
							'-content' => 'XML::Mini',
					),
				),
				array(
					'font'	=> array(
							'size'	=> '-1',
							'color'	=> '#3333cc',
							'-content' => 'The table below was generated with php - hooray.',
						),
				),
				
				array(
					'align'	=> 'center',
					'table'	=> array( 'cellpadding'	=> 5 ),
				),
				
				array(
					'align'	=> 'left',
					'-content' => '============================',
					'table'	=> array(
							'width'	=> '75%',
							'align'	=> 'center',
							'tr'	=> array(
								     array(
									'td' => array(
											'b' => "And here is the output of \$htmlDoc->getValue()",
											'br'	=> '',
											'-content' => $htmlDoc->getValue(),
										),
									),
								),
					),
				)
				
		), # end list of <p>s
  ), # end of <Body>
 ), # end of <html>
); # end of hash

$options = array(
		'attributes'	=> array(
					'body'	=> array('bgcolor', 'link', 'vlink'),
					'-all'	=> array('align', 'color'),
					'a'	=> 'href',
					'font'	=> 'size',
					'table'	=> array('cellpadding', 'cellspacing'),
					
				),
	);

$htmlDoc->fromArray($htmlArray, $options);

print $htmlDoc->toString();

?>
