<script language="javascript" type="text/javascript" src="[+mce_url+]tiny_mce/tiny_mce.js?[+refresh_seed+]"></script>
<script language="javascript" type="text/javascript" src="[+mce_url+]js/xconfig.js"></script>
<style type="text/css">
    .clearlooks2_modalBlocker {background-color:#333;}
    .defaultSkin table.mceToolbar, .defaultSkin tr.mceFirst .mceToolbar tr td, .defaultSkin tr.mceLast .mceToolbar tr td {border:0; margin:0; padding:0!important;}
</style>
