<form id="category-edit-form" action="<?php echo $view->get('url'); ?>" method="post">

  <p class="element-edit-message">Change category name or delete category from the Manager.</p>
  
  <table id="category-edit" class="grid" cellpadding="1" cellspacing="1">
    <thead>
      <tr>
        <td class="gridHeader"><?php echo $view->txt('Assigned elements'); ?></td>
        <td class="gridHeader"><?php echo $view->txt('Edit name'); ?></td>
        <td class="gridHeader"><?php echo $view->txt('Mark for deletion'); ?></td>
        <td class="gridHeader"><?php echo $view->txt('Delete immediately'); ?></td>
      </tr>
    </thead>
    <tbody>
      <?php $i = 0; foreach( $data as $category ) : ?>
      <tr>
        <td class="assigned <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <img class="tooltip_dom" src="../assets/modules/<?php echo $view->get('dirname'); ?>/skin/img/information.png" alt="<?php echo $view->txt('Show assigned elements'); ?>" title="DOM:assigned-elements-<?php echo $category['id']; ?>" />
          <div id="assigned-elements-<?php echo $category['id']; ?>"><?php $view->renderView( 'chunks/edit/assigned_elements', $view->getAllAssignedElements( $category['id'] ) ); ?></div> 
        </td>
        <td class="input <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <input type="hidden" name="<?php echo $view->get('request_key'); ?>[edit][data][<?php echo $category['id'] ?>][rank]" value="<?php echo $category['rank']; ?>" />
          <input type="hidden" name="<?php echo $view->get('request_key'); ?>[edit][data][<?php echo $category['id'] ?>][origin]" value="<?php echo urlencode( $category['category'] ); ?>" />
          <input type="text" name="<?php echo $view->get('request_key'); ?>[edit][data][<?php echo $category['id'] ?>][category]" value="<?php echo htmlspecialchars( $category['category'] ); ?>" />
        </td>           
        <td class="mark_delete <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <input type="checkbox" name="<?php echo $view->get('request_key'); ?>[edit][data][<?php echo $category['id'] ?>][delete]" value="1" />              
        </td>
        <td class="delete <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <a class="tooltip" href="<?php echo $view->get('url'); ?>&amp;<?php echo $view->get('request_key'); ?>[delete]=<?php echo $category['id']; ?>&amp;<?php echo $view->get('request_key'); ?>[category]=<?php echo urlencode($category['category']); ?>" title="<?php echo htmlspecialchars( $category['category'] ) ?>::<?php echo sprintf( $view->txt('Delete &quot;%s&quot; immediately'),htmlspecialchars( $category['category'] ) ); ?>"><?php echo $view->txt('Delete'); ?></a>             
        </td>
      </tr>
      <?php $i++; endforeach; ?>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="4" class="submit">
          <input type="submit" name="<?php echo $view->get('request_key'); ?>[edit][submit]" value="<?php echo $view->txt('Update categories'); ?>" />    
        </td>
      </tr>
    </tfoot>
  </table>
</form>