<form id="category-edit-form" action="<?php echo $view->get('url'); ?>" method="post">
  <input name="<?php echo $view->get('request_key'); ?>[edit][submit]" type="hidden" value="1" />
  <ul class="actionButtons">
    <li><a class="primary" href="#" onclick="document.getElementById('category-edit-form').submit();return false;"><?php echo $view->txt('cm_update_categories'); ?></a></li>
    <li><a href="#" id="edit-help"><?php echo $_lang['help']; ?></a></li>
  </ul>
  <div id="edit-info" style="display:none">
    <p class="element-edit-message">Change category name or delete category from the Manager.</p>
  </div>
  <script>
    jQuery( "#edit-help" ).click(function() {
      jQuery( '#edit-info').toggle();
    });
  </script>
  <table id="category-edit" class="grid" cellpadding="1" cellspacing="1">
    <thead>
      <tr>
        <td class="gridHeader"><?php echo $view->txt('cm_assigned_elements'); ?></td>
        <td class="gridHeader"><?php echo $view->txt('cm_edit_name'); ?></td>
        <td class="gridHeader"><?php echo $view->txt('cm_mark_for_deletion'); ?></td>
        <td class="gridHeader"><?php echo $view->txt('cm_delete_now'); ?></td>
      </tr>
    </thead>
    <tbody>
      <?php $i = 0; foreach( $data as $category ) : ?>
      <tr>
        <td class="assigned <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
            <button class="btn collapsed mootooltip_dom" type="button" data-toggle="collapse" data-target="#collapse-edit-<?php echo $i; ?>" aria-expanded="false" aria-controls="#collapse-edit-<?php echo $i; ?>" title="DOM:assigned-elements-<?php echo $category['id']; ?>">
            <i class="fa fa-info-circle" aria-hidden="true" /></i>
          </button>
          <div id="assigned-elements-<?php echo $category['id']; ?>"><?php $view->renderView( 'chunks/edit/assigned_elements', $view->getAllAssignedElements( $category['id'] ) ); ?></div> 
        </td>
        <td class="input <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <input type="hidden" name="<?php echo $view->get('request_key'); ?>[edit][data][<?php echo $category['id'] ?>][rank]" value="<?php echo $category['rank']; ?>" />
          <input type="hidden" name="<?php echo $view->get('request_key'); ?>[edit][data][<?php echo $category['id'] ?>][origin]" value="<?php echo urlencode( $category['category'] ); ?>" />
          <input type="text" name="<?php echo $view->get('request_key'); ?>[edit][data][<?php echo $category['id'] ?>][category]" value="<?php echo htmlspecialchars( $category['category'] ); ?>" />
        </td>           
        <td class="mark_delete <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <input type="checkbox" name="<?php echo $view->get('request_key'); ?>[edit][data][<?php echo $category['id'] ?>][delete]" value="1" />              
        </td>
        <td class="delete <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <a class="mootooltip" onclick="return confirm('<?php echo $view->txt('are_you_sure'); ?>')" href="<?php echo $view->get('url'); ?>&amp;<?php echo $view->get('request_key'); ?>[delete]=<?php echo $category['id']; ?>&amp;<?php echo $view->get('request_key'); ?>[category]=<?php echo urlencode($category['category']); ?>" title="<?php echo htmlspecialchars( $category['category'] ) ?>::<?php echo sprintf( $view->txt('cm_delete_element_x_now'),htmlspecialchars( $category['category'] ) ); ?>"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> <?php echo $view->txt('delete'); ?></a>             
        </td>
      </tr>
      <tr class="collapse" id="collapse-edit-<?php echo $i; ?>">
          <td colspan="4">
            <?php $view->renderView( 'chunks/edit/assigned_elements_collapse', $view->getAllAssignedElements( $category['id'] ) ); ?>
          </td>
      </tr>
      <?php $i++; endforeach; ?>
    </tbody>
  </table>
</form>