<form id="categories-sort-form" method="post" action="<?php echo $view->get('url'); ?>">

  <p class="element-edit-message">Drag category up or down to change its rank. Can be very useful when used with <a href="https://github.com/pmfx/CategorizedTabs" target="_blank">CategorizedTabs</a> plugin to change tabs order.</p>
  
  <table class="grid" cellpadding="1" cellspacing="1">
    <thead>
      <tr>
        <td class="gridHeader"><?php echo $view->txt('Category') ?></td>
        <td class="gridHeader"><?php echo $view->txt('Position') ?></td>
      </tr>
    </thead>
    <tbody id="categories-sort">
      <?php $i = 0; foreach( $data as $category ) : ?>
      <tr style="cursor:move">
        <td class="name <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <?php echo $category['category'] ?>
        </td>
        <td class="sort <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <input type="hidden" class="sort" name="<?php echo $view->get('request_key'); ?>[sort][data][<?php echo $category['id'] ?>][rank]" value="<?php echo $category['rank'] ?>" />
          <input type="hidden" name="<?php echo $view->get('request_key'); ?>[sort][data][<?php echo $category['id'] ?>][id]" value="<?php echo $category['id'] ?>" />
          <input type="hidden" name="<?php echo $view->get('request_key'); ?>[sort][data][<?php echo $category['id'] ?>][category]" value="<?php echo urlencode( $category['category'] ) ?>" />
          <span class="sort"><?php echo $category['rank'] ?></span>

          <!-- <span class="handle"><img src="mover.gif" /></span> -->
        </td>
      </tr>              
      <?php $i++; endforeach; ?>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2" class="submit">
          <input type="submit" name="<?php echo $view->get('request_key'); ?>[sort][submit]" value="<?php echo $view->txt('Save new sorting'); ?>" />
        </td>
      </tr>
    </tfoot>
  </table>
</form>
