<form id="categories-sort-form" method="post" action="<?php echo $view->get('url'); ?>">
	<input name="<?php echo $view->get('request_key'); ?>[sort][submit]" type="hidden" value="1" />
	<ul class="actionButtons">
		<li><a class="primary" href="#" onclick="document.getElementById('categories-sort-form').submit();return false;"><?php echo $view->txt('cm_save_new_sorting'); ?></a></li>
		<li><a href="#" id="sort-help"><?php echo $_lang['help']; ?></a></li>
	</ul>
	<div id="sort-info" style="display:none">
        <p class="element-edit-message">Drag category up or down to change its rank. Can be very useful when used with <a href="https://github.com/pmfx/CategorizedTabs" target="_blank">CategorizedTabs</a> plugin to change tabs order.</p>
	</div>
	<script>
		jQuery( "#sort-help" ).click(function() {
			jQuery( '#sort-info').toggle();
		});
	</script>
  <table class="grid" cellpadding="1" cellspacing="1">
    <thead>
      <tr>
        <td class="gridHeader"><?php echo $view->txt('category_heading') ?></td>
        <td class="gridHeader"><?php echo $view->txt('position') ?></td>
      </tr>
    </thead>
    <tbody id="categories-sort">
      <?php $i = 0; foreach( $data as $category ) : ?>
      <tr style="cursor:move">
        <td class="name <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <?php echo $category['category'] ?>
        </td>
        <td class="sort <?php echo ($i%2===0)?'gridItem':'gridAltItem'; ?>">
          <input type="hidden" class="sort" name="<?php echo $view->get('request_key'); ?>[sort][data][<?php echo $category['id'] ?>][rank]" value="<?php echo $category['rank'] ?>" />
          <input type="hidden" name="<?php echo $view->get('request_key'); ?>[sort][data][<?php echo $category['id'] ?>][id]" value="<?php echo $category['id'] ?>" />
          <input type="hidden" name="<?php echo $view->get('request_key'); ?>[sort][data][<?php echo $category['id'] ?>][category]" value="<?php echo urlencode( $category['category'] ) ?>" />
          <span class="sort"><?php echo $category['rank'] ?></span>

          <!-- <span class="handle"><img src="mover.gif" /></span> -->
        </td>
      </tr>              
      <?php $i++; endforeach; ?>
    </tbody>    
  </table>
</form>
