<table class="grid">
	<thead>
	<tr>
	<?php foreach( $data as $element => $items ) : ?>
		<td><?php echo $view->txt( $element ); ?></td>
	<?php endforeach; ?>
	</tr>
	</thead>
	<tbody>
	<tr>
	<?php foreach( $data as $element => $items ) : ?>
		<?php if( empty( $items ) ) : ?>
			<td><p class="no_assigned_elements"><?php echo $view->txt( 'none' ); ?></p></td>
		<?php else: ?>
			<td>
				<ul>
				<?php foreach( $items as $item ) : ?>
					<li><?php echo (strtolower($element)==='templates')? $item['templatename'] : $item['name']; ?></li>
				<?php endforeach; ?>
				</ul>
			</td>
		<?php endif; ?>
	<?php endforeach; ?>
	</tr>
	</tbody>
</table>